version: 0.2
run-as: root
phases: 
  install:
    runtime-versions:
      nodejs: 12
    commands:
      - npm install -g serverless
      - npm install
  build:
    commands:
      - serverless deploy
  post_build:
    commands:
      - eco "run tests here"
cache:
  paths:
    - node_modules