version: 0.2
run-as: root
phases: 
  install:
    runtime-versions:
      nodejs: 12
    commands:
      - n 14.18.3
      - npm install -g serverless
      - npm install
  build:
    commands:
      - serverless deploy
cache:
  paths:
    - node_modules